# Generated by Django 6.0.3 on 2026-03-27 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='notes',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción / Notas'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category', verbose_name='Categoría'),
        ),
    ]
